### ISSUE TITLE
The version isn't properly set in publishing tasks

### ISSUE THREAD

**Issue by martinvisser** [ethauvin/semver-gradle#10]
Same project with Gradle 7.2 sets the version during the build (?) phase so it is available during for example `publishToMavenLocal`, but with Gradle 7.3 it isn't and is set to / kept at "unspecified".

Generated pom file with Gradle 7.2:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example.plugin</groupId>
  <artifactId>com.example.plugin.gradle.plugin</artifactId>
  <version>0.3.0+20211125105833</version>
  <packaging>pom</packaging>
  <name>Example plugin</name>
  <description>Example</description>
  <dependencies>
    <dependency>
      <groupId>com.example</groupId>
      <artifactId>example-gradle-plugin</artifactId>
      <version>0.3.0+20211125105833</version> <!-- with the proper value -->
    </dependency>
  </dependencies>
</project>
```

Generated pom file with Gradle 7.3:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example.plugin</groupId>
  <artifactId>com.example.plugin.gradle.plugin</artifactId>
  <version>0.3.0+20211125105833</version>
  <packaging>pom</packaging>
  <name>Example plugin</name>
  <description>Example</description>
  <dependencies>
    <dependency>
      <groupId>com.example</groupId>
      <artifactId>example-gradle-plugin</artifactId>
      <version>unspecified</version> <!-- missing the proper value -->
    </dependency>
  </dependencies>
</project>
```

`version.properties`:
```
version.buildmeta=20211125105833
version.major=0
version.minor=3
version.patch=0
version.prerelease=
version.semver=0.3.0+20211125105833
```

Relevant gradle configuration (Kotlin DSL version):
```kotlin
plugins {
    `java-gradle-plugin`
    `maven-publish`
    idea
    `kotlin-dsl`
    id("net.thauvin.erik.gradle.semver") version "1.0.4"
}

gradlePlugin {
    plugins {
        create("example") {
            id = "com.example.plugin"
            implementationClass = "com.example.ExamplePlugin"
            displayName = "Example plugin"
            description = "Example"
        }
    }
}

publishing {
    repositories {
        maven {
            url =
                uri("https://example.com/artifactory")

            credentials {
                username = "user"
                password = "pwd"
            }
        }
    }
}
```

**Comment by ethauvin** [comment]
@martinvisser Looks like your project depends on itself, right? 

Publish/pTML is using the right version, it's the dependency that is failing.  Do you have a runnable example I can look at?

Generally, you can fix the problem by specifying the version in a `doFirst` or `postEvalute` closure, per the [documentation](https://github.com/ethauvin/semver-gradle#version-is-unspecified).

**Comment by martinvisser** [comment]
@ethauvin what do you mean with depends on itself? They're actually different artifacts, but the names look very similar. I also didn't know, but that's apparently how such a plugin's pom is generated.

I added an example: https://github.com/martinvisser/semver-gradle73
It generates two artifacts in maven local, the one with the gradle plugin (locate in `.m2/repository/com/example/plugin/semver/com.example.plugin.semver.gradle.plugin/1.0.1` contains the plugin with a dependency with version `unspecified`.

If I would do `doFirst` or `postEvaluate` where would you suggest to add that, to which task? I didn't add any tasks for example and this did work in gradle 7.2.

**Comment by martinvisser** [comment]
Okay, this actually fails with 7.2 as well. The command I ran is `./gradlew incrementPatch clean publishToMavenLocal`. After this I have `1.0.2` as project, but `1.0.1` as dependency version. Somewhere the order of operations indeed goes wrong, but now I don't think it's the semver plugin do be honest.

I'll have a second look.

**Comment by martinvisser** [comment]
As a workaround I now split the command in to: first increment, then publish.

**Comment by ethauvin** [comment]
@martinvisser Good investigative work! I've been there.

One thing I've discovered the hard way that might help you. Some plugins, especially the ones that have their own `version` property, will show `undefined` unless you set the property:

`version = project.version`

As mentioned before, this may also need to be in a `doFirst` closure.

Hope this helps.

**Comment by martinvisser** [comment]
@ethauvin I had another look at this issue, but I can't say I know what to do. There is as far as I can see no way to change the behaviour of the publishing task. The moment `generatePomFileForExamplePluginMarkerMavenPublication` is called the version isn't configured properly an results in something like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example.plugin.semver</groupId>
  <artifactId>com.example.plugin.semver.gradle.plugin</artifactId>
  <version>1.0.1</version>
  <packaging>pom</packaging>
  <name>Example</name>
  <description>Description</description>
  <dependencies>
    <dependency>
      <groupId>com.example</groupId>
      <artifactId>semver-gradle73</artifactId>
      <version>unspecified</version> <!-- version is not set properly -->
    </dependency>
  </dependencies>
</project>
```

The version is set with Gradle 7.2 and lower, but not if two tasks are combined: `./gradlew incrementPatch generatePomFileForExamplePluginMarkerMavenPublication` generates the following:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example.plugin.semver</groupId>
  <artifactId>com.example.plugin.semver.gradle.plugin</artifactId>
  <version>1.0.1</version>
  <packaging>pom</packaging>
  <name>Example</name>
  <description>Description</description>
  <dependencies>
    <dependency>
      <groupId>com.example</groupId>
      <artifactId>semver-gradle73</artifactId>
      <version>1.0.0</version>
    </dependency>
  </dependencies>
</project>
```

The `version.properties` file is updated in both cases.
```properties
#Generated by the Semver Plugin for Gradle
#Tue Dec 21 13:35:02 CET 2021
version.buildmeta=
version.major=1
version.minor=0
version.patch=1
version.prerelease=
version.semver=1.0.1
```

I have no clue on how to change the behaviour of the publishing plugin itself, as that's part of Gradle. I played around with `publications` as configuration of that plugin, trying to set the version there, but nothing seems to help.

```kotlin

publishing {
    publications {
         // or beforeEvaluate, or omitted, version is the previous value (in 7.2, unspecified in 7.3) if done with two tasks in one go
        afterEvaluate {
            all {
                version = project.version // if hard coded, this is picked up though
            }
        }
    }

    repositories {
        mavenLocal()
    }
}
```

**Comment by ethauvin** [comment]
@martinvisser In your pom `<version>` is set to `1.0.1` at the top. Is that the correct semver version number? I'm not seeing a difference in behavior between Gradle 7.2 and 7.3 on my own projects; the project version is set correctly on `publishToMavelLocal`, etc.

I guess I'm confused as to why the semver version is used as a dependency. It is intended to set the project version, not dependencies. I looked at your example and I'm not seeing where the dependency version is set. Your example seems to work as it should with Gradle 7.3.

If you want to update your example, I'll gladly look at it.

**Comment by martinvisser** [comment]
As it turns out it's really just Gradle itself and apparently just not working as expected. Is do see a difference between 7.2 and 7.3, but I have the feeling it relates to https://github.com/gradle/gradle/issues/4783.
Doing a manual publication works as expected, like this:

```kotlin
gradlePlugin {
    isAutomatedPublishing = false

    plugins {
        register("example") {
            id = "com.example.plugin.semver"
            implementationClass = "com.example.plugin.ExamplePlugin"
            displayName = "Example"
            description = "Description"
        }
    }
}

publishing {
    repositories {
        mavenLocal()
    }

    publications {
        register<MavenPublication>("pluginMaven") {
            from(components["java"])
        }

        register<MavenPublication>("examplePluginMarkerMaven") {
            groupId = gradlePlugin.plugins["example"].id
            artifactId = gradlePlugin.plugins["example"].id + ".gradle.plugin"
            pom.withXml {
                asNode().appendNode("name", gradlePlugin.plugins["example"].displayName)
                asNode().appendNode("description", gradlePlugin.plugins["example"].description)
                val dependency = asNode().appendNode("dependencies").appendNode("dependency")
                dependency.appendNode("groupId", group)
                dependency.appendNode("artifactId", rootProject.name)
                dependency.appendNode("version", version)
            }
        }
    }
}
```
