### ISSUE TITLE
Unable to use semver in CI pipeline

### ISSUE THREAD

**Issue by mochadwi** [ethauvin/semver-gradle#11]
```
* What went wrong:
Plugin [id: 'net.thauvin.erik.gradle.semver', version: '1.0.4'] was not found in any of the following sources:
- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'net.thauvin.erik.gradle.semver:net.thauvin.erik.gradle.semver.gradle.plugin:1.0.4')
  Searched in the following repositories:
    Gradle Central Plugin Repository
```

not sure if this is the internet problems(?) or my gradle, lmk if there's any information you need to know

**Comment by ethauvin** [comment]
Not sure what you're doing wrong, but the plugin is in the Gradle repository:

https://plugins.gradle.org/plugin/net.thauvin.erik.gradle.semver/1.0.4

**Comment by mochadwi** [comment]
checking, I'm afraid there's a problems when using https://github.com/jmfayard/refreshVersions/

**Comment by mochadwi** [comment]
seems our on-premise CI was using unstable connection and affects everything related to fetching

**Comment by mochadwi** [comment]
thanks for the quick response ❤️
