### ISSUE TITLE
Upgrade kotlin version to above 1.4

### ISSUE THREAD

**Issue by rickyrattlesnake** [ethauvin/semver-gradle#12]
I'm seeing this error using gradle 7.3.3 and kotlin 1.6 

```
w: Language version 1.4 is deprecated and its support will be removed in a future version of Kotlin
e: warnings found and -Werror specified
```

I think this comes from the `apiVersion` in https://github.com/ethauvin/semver-gradle/blob/master/build.gradle.kts 

Can this be upgraded ?

**Comment by ethauvin** [comment]
@rickyrattlesnake I'm using Gradle 7.3.3 and Kotlin 1.6.10 too, and am not seeing any warnings.

The easiest way to determine if the plugin is causing the error is to comment it out in your build file.
