### ISSUE TITLE
Set prerelease from commandline

### ISSUE THREAD

**Issue by ronaldvaneede** [ethauvin/semver-gradle#3]
Does the plugin support setting the prerelease from the commandline or with a task like incrementBuildMeta task? 
I would like to be able to do so.

**Comment by ethauvin** [comment]
That's a good idea. Thanks.

I've just implemented it in https://github.com/ethauvin/semver-gradle/commit/16d1a06571b11f51d60c2f148ba293a6ba3edbdc

You can now specify any of the `minor`, `major`, `path`, `prerelease` and `build` version from the command line as follows:

```
./gradlew -Dversion.prerelease=alpha ...
```

Test it out and let me know if that works for you.

If you don't know how to test it out, it's easy. First clone, then build to your local maven repo:

```
./gradlew publishToMavenLocal
```
then cd to `examples/test` and run:

```
./gradlew -Dversion.prerelease=beta run
```

**Comment by ronaldvaneede** [comment]
Hi, I can see this output when I run `./gradlew -Dversion.prerelease=master run`

`Parallel execution is an incubating feature.

> Configure project :
Please specify the version in version.properties and remove it from build.gradle

> Task :run
Version: 1.0.0-**master**
> cat version.properties
#Generated by the Semver Plugin for Gradle
#Thu Apr 11 09:08:56 CEST 2019
version.major=1
version.meta=
version.minor=0
version.patch=0
version.prerelease=`

The version info is not written to the version.properties file. Is that intended to be so?

**Comment by ronaldvaneede** [comment]
It is when I run `./gradlew -Dversion.prerelease=master incrementBuildMeta` 
That would be fine for me because I will probably run it like `./gradlew -Dversion.prerelease=master incrementBuildMeta build` but I was wondering if that was your intention.

**Comment by ethauvin** [comment]
@rveede No, it should modify the properties file. It's a bug. Thanks.

 If you run the command a second time, it should write to the properties file.

```
gradle -Dversion.prerelease=master run

> Configure project :
Please specify the version in version.properties and remove it from build.gradle

> Task :run
Version: 1.0.0-master
> cat version.properties
#Generated by the Semver Plugin for Gradle
#Thu Apr 11 00:41:26 PDT 2019
version.major=1
version.meta=
version.minor=0
version.patch=0
version.prerelease=master
```
I'll work on a fix.

**Comment by ethauvin** [comment]
@rveede That took a little bit more work than I thought it would, But it should now work in https://github.com/ethauvin/semver-gradle/commit/ad2a7ae78676cad5a2cd29b8fd9c74fc44958d81

I've done some minimal testing, so anything you can do would be greatly appreciated.

**Comment by ronaldvaneede** [comment]
I did a bit of testing and it seems to work. Did not see anything unexpected.

**Comment by ronaldvaneede** [comment]
I do have an issue trying to set semver from the commandline with `./gradlew -Dversion.semver=1.0.0-test run`
I get 
```
* What went wrong:
A problem occurred configuring root project 'examples-test'.
> Failed to notify project evaluation listener.
   > kotlin.text.StringsKt.clear(Ljava/lang/StringBuilder;)Ljava/lang/StringBuilder;
```

with
```
Caused by: java.lang.NoSuchMethodError: kotlin.text.StringsKt.clear(Ljava/lang/StringBuilder;)Ljava/lang/StringBuilder;
        at net.thauvin.erik.gradle.semver.Utils.parseSemVer(Utils.kt:147)
```
I am not so familiar with Kotlin but it looks to me that according to the documentation the StringBuilder's clear() method is not available on the JVM? 
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/-string-builder/index.html

**Comment by ethauvin** [comment]
@rveede That's funky. I get the same error, but I don't get it if I use `gradle` instead of `./gradlew`. Same versions too. Gotta figure that one out.

**Comment by ethauvin** [comment]
@rveede I was able to get it to work by removing the `.gradle` folder. I'm not quite sure why, the only thing I can think of is that I upgraded to Kotlin 1.3.30.

Let me know if that works for you.

**Comment by ronaldvaneede** [comment]
That helped. Did a bit of testing with -Dversion.semver= but so far I could not break it.
