### ISSUE TITLE
Access semver version properties in Gradle build file.

### ISSUE THREAD

**Issue by LeoColman** [ethauvin/semver-gradle#8]
Hey!
How can I read the version properties?

Currently I'm loading them manually

```
val props = Properties().apply {
    load(file("version.properties").inputStream())
}
```

Is there an easy way to do it?

**Comment by ethauvin** [comment]
@Kerooker If your project is in Java or Kotlin, you can use the [SemVer Annotation Processor](https://github.com/ethauvin/semver) to create a version class that is accessible programmatically within your project.

If you are trying to read the properties file in the Gradle build file, then what you suggested works.

I've never really thought about exposing the properties file content. Maybe as project extensions? Is that what you're looking for?

**Comment by LeoColman** [comment]
I have the need to embed the version to other gradle tasks, such as Google App Engine's `release` or for Android artifact creation.

I'm using the file approach, but I think that perhaps there should be a way to do it out-of-the-box. Something like

```
android {
     version = semver.version
     build = semver.major * 10000 + semver.minor * 100 + semver.patch
}
```

(This is actually pretty close to my use case)

**Comment by LeoColman** [comment]
And then we can remove user's trouble on fetching these to use in build.gradle

**Comment by ethauvin** [comment]
Have you tried?

`version = project.version`

That should work, if not try putting it in a `doFirst` block.

As far as your `build` calculation, I'd have to look into it. Providing read-only properties in Gradle is not very straight forward.

**Comment by ethauvin** [comment]
@Kerooker I've released 1.0.3-beta. It implements a set of semver extension properties. Look at the [documentation](https://github.com/ethauvin/semver-gradle#semver-extension-properties) for a complete list. 

Your example should now work as-is. Give it a try and let me know if that works for you.

**Comment by LeoColman** [comment]
That's exactly what I wanted!

This works as expected

**Comment by ethauvin** [comment]
Implemented by e1891c47af347f38a899af465a9210c2428d6976

**Comment by mochadwi** [comment]
How to make sure to assign the `semver.version` for `android.defaultConfig.versionName`? moving it to `afterEvaluate` making the `BuildConfig.VERSION_NAME` not exist (which we use internally in our project)

**Comment by ethauvin** [comment]
@mochadwi I'm not quite sure what you're trying to accomplish. Do you have an example or a project that I can look at?

**Comment by mochadwi** [comment]
```
android {

   defaultConfig {
       // no. 1
       versionName = semver.version // will assign a default value, e.g: 1.0.0
       project.afterEvaluate {
           // No. 2

           versionName = semver.version // actual version assigned, e.g: 2.1.1

       }

   }
}
```


In our case we need to assign the `versionName` in No. 1 to generate `BuildConfig.VERSION_NAME`, but as mentioned in the docs, we need use `afterEvaluate`, `doLast` or `doFirst` to assign the correct value. 


When updating to use no. 2, seems the `BuildConfig.VERSION_NAME` not generated anymore, as `BuildConfig.VERSION_NAME` only generated in _**Configuration Phase**_ (cmiiw) 


We're ended up using the `readLines` files manually to get the correct `semver.version`

**Comment by ethauvin** [comment]
@mochadwi I have no idea if it'll work, but you could try:

```groovy
versionName = ${-> semver.version}
```

It might work, let me know.

**Comment by mochadwi** [comment]
Thanks, will let you know ASAP 🙏

**Comment by mochadwi** [comment]
> @mochadwi I have no idea if it'll work, but you could try:
> 
> ```groovy
> versionName = ${-> semver.version}
> ```
> 
> It might work, let me know.

is it Lambda argument? needs to find an alternative for `build.gradle.kts` (kotlin script)

> never came across this though :D

**Comment by ethauvin** [comment]
@mochadwi It's a [lazy instantiation of a GString](https://blog.mrhaki.com/2016/02/gradle-goodness-lazy-task-properties.html). I don't think there's an equivalent in Kotlin, unfortunately.

Have you tried setting the version as a late variable? Might work, but I have my doubts.

**Comment by mochadwi** [comment]
Thanks for the reference, will update you later. Currently still AFK 🙏

**Comment by mochadwi** [comment]
> @mochadwi It's a [lazy instantiation of a GString](https://blog.mrhaki.com/2016/02/gradle-goodness-lazy-task-properties.html). I don't think there's an equivalent in Kotlin, unfortunately.
> 
> Have you tried setting the version as a late variable? Might work, but I have my doubts.

Does the `late variable` different with the `lazy instantiation`?
