### ISSUE TITLE
Make version available for execution phase of gradle build.

### ISSUE THREAD

**Issue by mitm001** [ethauvin/semver-gradle#9]
When trying to access the `$version` variable for the plugin during an task of `type: exec` (execution phase) it's undefined.

Would it be possible to use lazy initialization for your plugin?

**Comment by ethauvin** [comment]
@mitm001 Couple things that you may want to try:

1. Wrap call in `doFirst()` or `doLast()`:

```gradle
task echoVersion(type:Exec) {
    doFirst {
        commandLine "echo", "$project.version"
    }
}
```
2. Use lazy instantation:

```gradle
task echoVersion(type:Exec) {
    commandLine "echo", "${-> project.version}"
}
```

Let me know if that works for you.

**Comment by mitm001** [comment]
2 works. 

I must admit, I have not seen the `->` explained in any gradle docs when accessing a variable.

**Comment by ethauvin** [comment]
@mitm001 Me neither, and I looked and looked when I ran into the same issue with one of my projects. I found a mention of it on [stackoverflow](https://stackoverflow.com/questions/27682676/how-can-i-make-gradle-extensions-lazily-evaluate-properties-that-are-set-dynamic).

**Comment by Masterzach32** [comment]
I'm having a similar issue, I'd like to access the version during configuration when using the Jib plugin to set the docker container tag to the project version. This is using the kotlin gradle dsl, and the workarounds above are not available in the jib block since it's not a task block.

My current workaround is to just read the version from the file, however this is not very nice as I have to copy it to every build file that I use jib and the semver plugin in. I also had to use this workaround with the docker-gradle plugin.

```kotlin
fun getVersionFromSemver() = file("version.properties")
    .readLines()
    .first { it.contains("version.semver") }
    .split("=")
    .last()
    .trim()
```

**Comment by ethauvin** [comment]
@Masterzach32 What's the value of `semver.semver` in the configuration stages of either plugins?

**Comment by Masterzach32** [comment]
`semver.semver` is "1.0.0" during the configuration stage. I got this by just logging the value inside of jib's config block.

**Comment by ethauvin** [comment]
@Masterzach32 Which means the semver-gradle plugin is not configured yet. Not sure if there's a way around that. I'm looking into it.

**Comment by ethauvin** [comment]
@Masterzach32 One possible workaround that I just [read about](https://github.com/toolebox-io/gradle-git-versioner#my-version-is-unspecified), try something like:

```gradle
jib {
    project.afterEvaluate {
         some_jib_property = semver.semver // or project.version
    }
}
```

Let me know if that works.

**Comment by Masterzach32** [comment]
That works, thanks!
